- packages/apollo-components/CHANGELOG.md
- packages/apollo-components/package.json
- packages/apollo-components/src/DataTable/components/TableHeader.tsx
- packages/apollo-components/src/DataTable/index.ts
- packages/apollo-components/src/cells/HeaderCell.tsx
[AB#313380](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/313380)
> ♿️ use aria-sort and implement header columns fixed width

- .github/PULL_REQUEST_TEMPLATE.md
> 🧑‍💻 add pr template

- .changeset/five-years-work.md
- packages/apollo-components/src/cells/DynamicCell.tsx
[AB#313380](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/313380)
> :sparkles: add custom color to dynamic cell

- .changeset/rotten-maps-heal.md
- packages/apollo-components/src/DataTable/components/BasicTable.tsx
- packages/apollo-components/src/DataTable/components/VirtualTable.tsx
> 🚸 Add pointer cursor to clickable rows

- README.md
> :memo: improve symlink documentation

- .changeset/nice-boxes-talk.md
- packages/apollo-components/src/cells/DynamicCell.tsx
> :sparkles: add background to sticky cell

- .changeset/chatty-mugs-train.md
- apps/playground/src/components/PokemonTable/PokemonTable.tsx
- packages/apollo-components/src/DataTable/components/TableRow.tsx
- packages/apollo-components/src/DataTable/types.ts
> ✨ Add row wrapper component to enable external contexts like hook form

- .changeset/shaggy-pants-brake.md
- packages/apollo-utils/src/zod-validation/utils.ts
> ✨ Add validateAsync to validator util

- .changeset/few-lions-march.md
- packages/tsconfig/base.json
- packages/tsconfig/vite.json
noEmit in base config
remove obsolete properties in vite.json, inherited from base
> :wrench: tsconfig improvements

- .changeset/quick-moles-admire.md
- apps/jotai-form-example/src/components/PokemonPage/PokemonTable.tsx
- apps/jotai-form-example/src/components/PokemonPage/columns.ts
- apps/jotai-form-example/src/components/PokemonPage/components/ActionsCell.tsx
- packages/apollo-components/src/AppShell/AppShell.tsx
- packages/apollo-components/src/DataTable/DataTableRaw.tsx
- packages/apollo-components/src/DataTable/components/BasicTable.tsx
- packages/apollo-components/src/DataTable/components/TableBody.tsx
- packages/apollo-components/src/DataTable/components/TableRow.tsx
- packages/apollo-components/src/DataTable/components/VirtualTable.tsx
- packages/apollo-components/src/DataTable/types.ts
- packages/apollo-components/src/DataTable/utils.tsx
- packages/apollo-components/src/cells/ChipsCell.tsx
- packages/apollo-components/src/cells/DynamicCell.tsx
- packages/apollo-components/src/cells/HeaderCell.tsx
- packages/apollo-components/src/cells/SelectColumnDef.tsx
- Add ability to set fixed column width
- Inherit cell color in sticky cell
- General issue across applications
- Major issue in https://github.com/equinor/cdl-bloomberg-enrichment
[AB#326650](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/326650)
[AB#326651](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/326651)
> 💄 add fixed width and background color to sticky cells

- .changeset/spotty-pandas-knock.md
> :green_heart: Resolve Changesets publish error

- .changeset/strange-pants-lay.md
> 💚 Resolve Changesets publish error

- .changeset/chatty-meals-push.md
> 🔖 Add changeset

- .changeset/nasty-carrots-behave.md
- packages/apollo-components/src/DataTable/components/TableRow.tsx
- packages/apollo-components/src/cells/TypographyCustom.tsx
- Fix active row color inheriting
- Fix cell padding
Bugs
[AB#330177](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/330177)
> 🐛 Fix active row color and cell padding

- .changeset/gorgeous-spiders-look.md
- packages/apollo-components/src/DataTable/components/VirtualTable.tsx
- packages/apollo-components/src/cells/HeaderCell.tsx
[AB#330519](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/330519)
> 🐛 Fix header z-index and rerender issue visually

- .github/workflows/storybook.yml
- .gitignore
- yarn.lock
publish apollo-components storybook to github pages
Storybook available at https://equinor.github.io/apollo-react-components/
quickly explore this library
> :hammer: Storybook gh pages

- .changeset/six-turkeys-vanish.md
- packages/apollo-components/package.json
- yarn.lock
[AB#344749](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/344749)
> ➖ Move deps to peerDeps

- .changeset/forty-cherries-wait.md
- packages/apollo-components/package.json
- yarn.lock
> 🐛 Move @equinor/eds-core-react to peer dependencies

- .changeset/happy-parrots-occur.md
- apps/jotai-form-example/src/features/unit-events-page/UnitEventsTable.tsx
- apps/jotai-form-example/src/features/unit-events-page/hooks/useUnitEventsQuery.ts
- packages/apollo-components/src/DataTable/DataTableRaw.tsx
- packages/apollo-components/src/DataTable/hooks/index.ts
- packages/apollo-components/src/DataTable/hooks/useFetchMoreOnBottomReached.tsx
- packages/apollo-components/src/DataTable/index.ts
- packages/apollo-components/src/DataTable/types.ts
- packages/mock-data/package.json
- packages/mock-data/src/unit-events/unitEvents.ts
- yarn.lock
> ✨ Add infinite scroll

- .changeset/afraid-rules-yawn.md
- packages/apollo-common/package.json
> ➖ Remove cyclic dependency

- .changeset/smart-keys-matter.md
- packages/apollo-common/package.json
> 📦️ Make common package private

- .changeset/beige-carpets-sin.md
- packages/apollo-common/package.json
> 📦️ Remove public tag

- .changeset/itchy-hornets-kiss.md
- packages/apollo-components/src/DataTable/components/PaddingRow.tsx
- packages/apollo-components/src/DataTable/components/VirtualTable.tsx
> 🚸 Increase overscan and block padding row interactivity

- .changeset/smooth-yaks-wave.md
- packages/apollo-components/src/form-meta/utils.tsx
> 🐛 Import omit directly to fix run time bug

- .changeset/perfect-houses-flash.md
- packages/apollo-components/src/DataTable/DataTable.tsx
> 🐛 Test numbers using regex

- .changeset/heavy-grapes-punch.md
- apps/jotai-form-example/src/features/unit-events-page/UnitEventsTable.tsx
- apps/playground/src/components/PokemonTable/PokemonTable.tsx
- packages/apollo-components/src/DataTable/DataTable.tsx
- packages/apollo-components/src/DataTable/components/TableHeader.tsx
- packages/apollo-components/src/DataTable/types.ts
- packages/apollo-components/src/cells/HeaderCell.tsx
Add column resizing to DataTable.
Improve UX.
[AB#369584](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/369584)
> ✨ Add column resizing (AB#369584)

- .changeset/eighty-cats-work.md
- packages/apollo-components/package.json
- packages/apollo-components/src/cells/PopoverCell.tsx
- yarn.lock
- Show empty string instead of "null" string in Popover Cell when value is `null`.
- Popover cell displays "null" for null values.
[AB#372536](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/372536)
> 🐛 Show empty string instead of null in popover cell

- .changeset/two-nails-count.md
- apps/playground/src/components/PokemonTable/PokemonTable.tsx
- apps/playground/src/components/PokemonTable/columns.ts
- packages/apollo-components/src/DataTable/DataTable.tsx
- packages/apollo-components/src/DataTable/types.ts
- packages/apollo-components/src/cells/DynamicCell.tsx
- packages/apollo-components/src/cells/HeaderCell.tsx
- packages/apollo-components/src/cells/utils.tsx
- yarn.lock
Add column pinning. Based on Mantine React Table.
> ✨ Add column pinning

- .changeset/sixty-donuts-provide.md
- packages/apollo-components/src/cells/HeaderCell.tsx
> 🐛 Fix sort icon shrinking

- .changeset/cuddly-plants-marry.md
- apps/jotai-form-example/package.json
- apps/playground/package.json
- packages/apollo-components/package.json
- packages/apollo-utils/package.json
- packages/eslint-config-custom/package.json
- packages/mock-data/package.json
- yarn.lock
> ⬆️ Upgrade typescript

- .changeset/eighty-socks-sit.md
- packages/eslint-config-custom/package.json
> 💚 Set eslint-config-custom to private

- .changeset/light-lies-wonder.md
[AB#389480](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/389480)
> 🔖 Increment version
